[tool.poetry]
name = "loops"
version = "0.1.0"
description = ""
authors = ["Mike Burton <michaelgburton@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pytest = "^7.4.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
